### ISSUE TITLE
Is this extension going to be dropped?

### ISSUE THREAD

**Issue by AlexMex90** [ozonos/atom-workspaces#3]
Is this extension being dropped or is this still a desired feature? 

I have some free time and I think I can tackle this, however the last time I attempted setting up an extension development environment I attempted to modify the Workspace grid extension but I wasn't able to install it or even find it on Tweak Tool. 

I can dedicate some time to it, but it would be better if somebody can give me a hand to get started.

**Comment by kyuucr** [comment]
AFAIK this still on the goal of this project.

You could ask @me4oslav for the design document. Unfortunately, I cannot give you exact step to what to study/code because the documentation for developing gnome extension looks complicated as hell. I could only say learn and copy from other extension that do the same thing you intend to do.

**Comment by UriHerrera** [comment]
All the extensions are meant to be used.. eventually. Of course they need to be created first, as @kyuucr has mentioned, you are better off starting with an extension similar to what this is supposed to do. We certainly lack developers so we can't help too much on that front.

**Comment by AlexMex90** [comment]
Yes, GNOME Shell extensions documentation is not very helpful, but I'll give it a go.
